name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  ga4:
    source_project: "{{ env_var('GA4_SOURCE_PROJECT', '<YOUR_GCP_PROJECT_ID>') }}"
    source_dataset: "{{ env_var('GA4_SOURCE_DATASET', '<YOUR_GA4_DATASET_PREFIX_OR_DATASET>') }}"
    start_date: "{{ env_var('GA4_START_DATE', '2024-01-01') }}"
    property_ids:
      - "{{ env_var('GA4_PROPERTY_ID', '<YOUR_GA4_PROPERTY_ID>') }}"
