name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  ga4:
    source_project: "portfolio-tom"
   # source_dataset: "{{ env_var('GA4_SOURCE_DATASET', '<YOUR_GA4_DATASET_PREFIX_OR_DATASET>') }}"
    property_ids: [111111111] # Array of properties to process
    start_date: "20201101" # Earliest date to load
    static_incremental_days: 3 # Number of days to scan and reprocess on each run
