name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Use the exact variable name 'project' because your model expects it
  project: "{{ env_var('GCP_PROJECT_ID') }}"
  dataset: "{{ env_var('GCP_DATASET') }}"
  
  ga4:
    source_project: "{{ env_var('GA4_SOURCE_PROJECT') }}"
   ## source_dataset: "{{ env_var('GA4_SOURCE_DATASET') }}"
    property_ids: ["{{ env_var('GA4_PROPERTY_ID') }}"]
    start_date: "{{ env_var('GA4_START_DATE') }}"
   ## static_incremental_days: 3
