version: 2

models:
  - name: mart_exec_daily_kpis
    description: "Executive daily KPI mart at date grain for top-line ecommerce performance."
    columns:
      - name: date
        description: "Calendar date for KPI aggregation."
        tests:
          - not_null
          - unique
      - name: revenue
        description: "Total purchase revenue for the date."
      - name: orders
        description: "Distinct transaction count for the date."
      - name: purchasers
        description: "Distinct purchasers (user_pseudo_id) for the date."
      - name: aov
        description: "Average order value (revenue/orders)."
      - name: sessions
        description: "Total sessions for the date."
      - name: engaged_sessions
        description: "Total engaged sessions for the date."
      - name: conversion_rate
        description: "Order conversion rate (orders/sessions)."
      - name: items_sold
        description: "Total item quantity sold for the date."

  - name: mart_channel_daily
    description: "Executive channel performance mart at date + channel grain."
    columns:
      - name: date_channel_key
        description: "Synthetic unique key for date + default channel grouping."
        tests:
          - not_null
          - unique
      - name: date
        description: "Calendar date for aggregation."
        tests:
          - not_null
      - name: default_channel_grouping
        description: "GA4 default channel grouping."
        tests:
          - not_null
      - name: source
        description: "Traffic source."
      - name: medium
        description: "Traffic medium."
      - name: sessions
        description: "Sessions attributed to channel."
      - name: revenue
        description: "Revenue attributed to channel."
      - name: orders
        description: "Orders attributed to channel."
      - name: purchasers
        description: "Distinct purchasers attributed to channel."
      - name: aov
        description: "Average order value by channel."
      - name: conversion_rate
        description: "Orders per session by channel."

  - name: mart_product_daily
    description: "Product performance mart at date + product grain."
    columns:
      - name: date_product_key
        description: "Synthetic unique key for date + product."
        tests:
          - not_null
          - unique
      - name: date
        description: "Calendar date for product metrics."
        tests:
          - not_null
      - name: item_id
        description: "GA4 item identifier."
      - name: item_name
        description: "GA4 item name."
      - name: item_category
        description: "GA4 item category."
      - name: item_revenue
        description: "Revenue generated by purchased item lines."
      - name: quantity
        description: "Quantity sold."
      - name: orders_with_item
        description: "Distinct orders containing the item."

  - name: mart_funnel_daily
    description: "Daily ecommerce funnel mart with session-level step counts and CVRs."
    columns:
      - name: date
        description: "Calendar date for funnel metrics."
        tests:
          - not_null
          - unique
      - name: view_item_sessions
        description: "Distinct sessions with at least one view_item event."
      - name: add_to_cart_sessions
        description: "Distinct sessions with at least one add_to_cart event."
      - name: begin_checkout_sessions
        description: "Distinct sessions with at least one begin_checkout event."
      - name: purchase_sessions
        description: "Distinct sessions with at least one purchase event."
      - name: cvr_view_to_cart
        description: "Session conversion rate from view_item to add_to_cart."
      - name: cvr_cart_to_checkout
        description: "Session conversion rate from add_to_cart to begin_checkout."
      - name: cvr_checkout_to_purchase
        description: "Session conversion rate from begin_checkout to purchase."
      - name: cvr_view_to_purchase
        description: "Session conversion rate from view_item to purchase."
